branch-defaults:
  default:
    environment: Custom-env
    group_suffix: null
  master:
    environment: null
    group_suffix: null
global:
  application_name: Hasvi-testing
  default_ec2_keyname: null
  default_platform: Node.js
  default_region: ap-southeast-2
  profile: eb-cli
  sc: git
